CREATE VIEW Q3_1
AS
SELECT Email, Name
FROM (CUSTOMER NATURAl JOIN ACCOUNT)
HAVING MAX(Reward_point);

CREATE VIEW Q3_2
AS
SELECT Isbn, Title
FROM (BOOK LEFT OUTER JOIN DISCOUNT)
WHERE Percentage IS NOT NULL
HAVING MAX(Price*Percentage);

CREATE VIEW Q3_3
AS
SELECT Isbn, Stock*Price
FROM BOOK NATURAL JOIN INVENTORY
WHERE Stock=SUM(Quantity) ;