-- Delete a BOOK
DELETE FROM BOOK
 WHERE ISBN = '0782140661';

DELETE FROM AUTHOR
 WHERE (SELECT ISBN
	        FROM (AUTHOR LEFT OUTER JOIN WIRTES)
         WHERE ISBN = '0782140661');

DELETE FROM WRITES
 WHERE ISBN = '0782140661';

DELETE FROM PUBLISHER
 WHERE (SELECT ISBN
	        FROM (PUBLISHER LEFT OUTER JOIN PUBLISHES)
         WHERE ISBN = '0782140661');

DELETE FROM PUBLISHES
 WHERE ISBN = '0782140661';

-- Delete a PUBLISHER
DELETE FROM PUBLISHER
 WHERE Name = 'Sybex';

DELETE FROM AUTHOR
 WHERE (SELECT Authorid
	        FROM WRITES
	       WHERE (SELECT ISBN
		              FROM PUBLISHES
		             WHERE Publisher = 'Sybex'));

DELETE FROM WRITES
 WHERE (SELECT ISBN
	        FROM PUBLISHES
	       WHERE Publisher = 'Sybex');

DELETE FORM BOOK
 WHERE (SELECT ISBN
          FROM (PUBLISHERES RIGHT OUTER JOIN BOOK)
         WHERE PUBLISHER.Publisher = 'Sybex');

DELETE FROM PUBLISHES
 WHERE Publisher = 'Sybex';

-- Delete an AUTHOR
DELETE FROM AUTHOR
 WHERE AuthoreId = '12345';

DELETE FROM PUBLISHER
 WHERE (SELECT Publisher
	        FROM PUBLISHES
	       WHERE (SELECT ISBN
		              FROM WRITES
		             WHERE AuthorId='12345'));

DELETE FROM PUBLISHES
 WHERE (SELECT ISBN
	        FROM WRITES
	       WHERE AuthorId='12345');

DELETE FORM BOOK
 WHERE (SELECT ISBN
          FROM (WRITES RIGHT OUTER JOIN BOOK)
         WHERE AuthorId='12345');

DELETE FROM WRITES
 WHERE AuthorId='12345';

-- Delete a CUSTOMER
DELETE FROM ACCOUNT
 WHERE Email = 'email@email.com'

DELETE FROM CUSTOMER
 WHERE Email = 'email@email.com'
