-- Delete a BOOK
DELETE FROM BOOK
 WHERE Isbn = '0782140661';

DELETE FROM AUTHOR
 WHERE (SELECT Isbn
	        FROM (AUTHOR LEFT OUTER JOIN WIRTES)
         WHERE Isbn = '0782140661');

DELETE FROM WRITES
 WHERE Isbn = '0782140661';

DELETE FROM PUBLISHER
 WHERE (SELECT Isbn
	        FROM (PUBLISHER LEFT OUTER JOIN PUBLISHES)
         WHERE Isbn = '0782140661');

DELETE FROM PUBLISHES
 WHERE Isbn = '0782140661';

-- Delete a PUBLISHER
DELETE FROM PUBLISHER
 WHERE Name = 'Sybex';

DELETE FROM AUTHOR
 WHERE (SELECT AuthorID
	        FROM WRITES
	       WHERE (SELECT Isbn
		              FROM PUBLISHES
		             WHERE Publisher = 'Sybex'));

DELETE FROM WRITES
 WHERE (SELECT ISBN
	        FROM PUBLISHES
	       WHERE Publisher = 'Sybex');

DELETE FROM BOOK
 WHERE (SELECT Isbn
          FROM (PUBLISHERES RIGHT OUTER JOIN BOOK)
         WHERE PUBLISHER.Publisher = 'Sybex');

DELETE FROM PUBLISHES
 WHERE Publisher = 'Sybex';

-- Delete an AUTHOR
DELETE FROM AUTHOR
 WHERE AuthorID = '12345';

DELETE FROM PUBLISHER
 WHERE (SELECT Publisher
	        FROM PUBLISHES
	       WHERE (SELECT Isbn
		              FROM WRITES
		             WHERE AuthorID='12345'));

DELETE FROM PUBLISHES
 WHERE (SELECT Isbn
	        FROM WRITES
	       WHERE AuthorID='12345');

DELETE FROM BOOK
 WHERE (SELECT Isbn
          FROM (WRITES RIGHT OUTER JOIN BOOK)
         WHERE AuthorID='12345');

DELETE FROM WRITES
 WHERE AuthorID='12345';

-- Delete a CUSTOMER
DELETE FROM ACCOUNT
 WHERE Email = 'email@email.com';

DELETE FROM CUSTOMER
 WHERE Email = 'email@email.com';
